# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gyro.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(925, 585)
        Form.setMinimumSize(QtCore.QSize(500, 585))
        Form.setStyleSheet("QLCDNumber {\n"
"    background-color: rgb(0,0,128);\n"
"    color: rgb(255,255,255);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.topLayout.addLayout(self.horizontalLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(225, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelGAUL = QtWidgets.QLabel(self.frame)
        self.labelGAUL.setGeometry(QtCore.QRect(10, 0, 201, 99))
        self.labelGAUL.setText("")
        self.labelGAUL.setPixmap(QtGui.QPixmap("img/GAUL_logo2.png"))
        self.labelGAUL.setScaledContents(True)
        self.labelGAUL.setObjectName("labelGAUL")
        self.groupBoxRot = QtWidgets.QGroupBox(self.frame)
        self.groupBoxRot.setGeometry(QtCore.QRect(10, 310, 211, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxRot.setFont(font)
        self.groupBoxRot.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxRot.setObjectName("groupBoxRot")
        self.lcdRz = QtWidgets.QLCDNumber(self.groupBoxRot)
        self.lcdRz.setGeometry(QtCore.QRect(70, 110, 71, 31))
        self.lcdRz.setStyleSheet("background-color: rgb(0,0,128)")
        self.lcdRz.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdRz.setObjectName("lcdRz")
        self.lcdRy = QtWidgets.QLCDNumber(self.groupBoxRot)
        self.lcdRy.setGeometry(QtCore.QRect(70, 70, 71, 31))
        self.lcdRy.setStyleSheet("background-color: rgb(0,95,0)")
        self.lcdRy.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdRy.setObjectName("lcdRy")
        self.lcdRx = QtWidgets.QLCDNumber(self.groupBoxRot)
        self.lcdRx.setGeometry(QtCore.QRect(70, 30, 71, 31))
        self.lcdRx.setStyleSheet("background-color: rgb(96,0,0)")
        self.lcdRx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdRx.setObjectName("lcdRx")
        self.labelRx = QtWidgets.QLabel(self.groupBoxRot)
        self.labelRx.setGeometry(QtCore.QRect(10, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelRx.setFont(font)
        self.labelRx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRx.setObjectName("labelRx")
        self.labelRy = QtWidgets.QLabel(self.groupBoxRot)
        self.labelRy.setGeometry(QtCore.QRect(10, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelRy.setFont(font)
        self.labelRy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRy.setObjectName("labelRy")
        self.labelRz = QtWidgets.QLabel(self.groupBoxRot)
        self.labelRz.setGeometry(QtCore.QRect(10, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelRz.setFont(font)
        self.labelRz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRz.setObjectName("labelRz")
        self.labelRxDeg = QtWidgets.QLabel(self.groupBoxRot)
        self.labelRxDeg.setGeometry(QtCore.QRect(150, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelRxDeg.setFont(font)
        self.labelRxDeg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRxDeg.setObjectName("labelRxDeg")
        self.labelRyDeg = QtWidgets.QLabel(self.groupBoxRot)
        self.labelRyDeg.setGeometry(QtCore.QRect(150, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelRyDeg.setFont(font)
        self.labelRyDeg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRyDeg.setObjectName("labelRyDeg")
        self.labelRzDeg = QtWidgets.QLabel(self.groupBoxRot)
        self.labelRzDeg.setGeometry(QtCore.QRect(150, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelRzDeg.setFont(font)
        self.labelRzDeg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRzDeg.setObjectName("labelRzDeg")
        self.groupBoxRotS = QtWidgets.QGroupBox(self.frame)
        self.groupBoxRotS.setGeometry(QtCore.QRect(10, 150, 211, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxRotS.setFont(font)
        self.groupBoxRotS.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxRotS.setObjectName("groupBoxRotS")
        self.lcdRSz = QtWidgets.QLCDNumber(self.groupBoxRotS)
        self.lcdRSz.setGeometry(QtCore.QRect(70, 110, 71, 31))
        self.lcdRSz.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdRSz.setObjectName("lcdRSz")
        self.lcdRSy = QtWidgets.QLCDNumber(self.groupBoxRotS)
        self.lcdRSy.setGeometry(QtCore.QRect(70, 70, 71, 31))
        self.lcdRSy.setStyleSheet("background-color: rgb(0,95,0)")
        self.lcdRSy.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdRSy.setObjectName("lcdRSy")
        self.lcdRSx = QtWidgets.QLCDNumber(self.groupBoxRotS)
        self.lcdRSx.setGeometry(QtCore.QRect(70, 30, 71, 31))
        self.lcdRSx.setStyleSheet("background-color: rgb(96,0,0)")
        self.lcdRSx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdRSx.setObjectName("lcdRSx")
        self.labelRSx = QtWidgets.QLabel(self.groupBoxRotS)
        self.labelRSx.setGeometry(QtCore.QRect(10, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelRSx.setFont(font)
        self.labelRSx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRSx.setObjectName("labelRSx")
        self.labelRSy = QtWidgets.QLabel(self.groupBoxRotS)
        self.labelRSy.setGeometry(QtCore.QRect(10, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelRSy.setFont(font)
        self.labelRSy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRSy.setObjectName("labelRSy")
        self.labelRSz = QtWidgets.QLabel(self.groupBoxRotS)
        self.labelRSz.setGeometry(QtCore.QRect(10, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelRSz.setFont(font)
        self.labelRSz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRSz.setObjectName("labelRSz")
        self.labelRSxDegS = QtWidgets.QLabel(self.groupBoxRotS)
        self.labelRSxDegS.setGeometry(QtCore.QRect(150, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelRSxDegS.setFont(font)
        self.labelRSxDegS.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRSxDegS.setObjectName("labelRSxDegS")
        self.labelRSyDegS = QtWidgets.QLabel(self.groupBoxRotS)
        self.labelRSyDegS.setGeometry(QtCore.QRect(150, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelRSyDegS.setFont(font)
        self.labelRSyDegS.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRSyDegS.setObjectName("labelRSyDegS")
        self.labelRSzDegS = QtWidgets.QLabel(self.groupBoxRotS)
        self.labelRSzDegS.setGeometry(QtCore.QRect(150, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelRSzDegS.setFont(font)
        self.labelRSzDegS.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRSzDegS.setObjectName("labelRSzDegS")
        self.labelAltM = QtWidgets.QLabel(self.frame)
        self.labelAltM.setGeometry(QtCore.QRect(160, 105, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelAltM.setFont(font)
        self.labelAltM.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAltM.setObjectName("labelAltM")
        self.labelAlt = QtWidgets.QLabel(self.frame)
        self.labelAlt.setGeometry(QtCore.QRect(20, 105, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelAlt.setFont(font)
        self.labelAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAlt.setObjectName("labelAlt")
        self.lcdAlt = QtWidgets.QLCDNumber(self.frame)
        self.lcdAlt.setGeometry(QtCore.QRect(80, 105, 71, 31))
        self.lcdAlt.setStyleSheet("background-color: black")
        self.lcdAlt.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdAlt.setObjectName("lcdAlt")
        self.rightLayout.addWidget(self.frame)
        self.timeLayout = QtWidgets.QFrame(Form)
        self.timeLayout.setMinimumSize(QtCore.QSize(0, 43))
        self.timeLayout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timeLayout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timeLayout.setObjectName("timeLayout")
        self.labelLaunchTime = QtWidgets.QLabel(self.timeLayout)
        self.labelLaunchTime.setGeometry(QtCore.QRect(5, 0, 221, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLaunchTime.sizePolicy().hasHeightForWidth())
        self.labelLaunchTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelLaunchTime.setFont(font)
        self.labelLaunchTime.setStyleSheet("/*background-color: rgb(0,0,128); color: rgb(255,255,255);*/")
        self.labelLaunchTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLaunchTime.setObjectName("labelLaunchTime")
        self.rightLayout.addWidget(self.timeLayout)
        self.topLayout.addLayout(self.rightLayout)
        self.topLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.topLayout)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        self.seekBar = QtWidgets.QSlider(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seekBar.sizePolicy().hasHeightForWidth())
        self.seekBar.setSizePolicy(sizePolicy)
        self.seekBar.setMinimumSize(QtCore.QSize(0, 22))
        self.seekBar.setMaximum(1000)
        self.seekBar.setOrientation(QtCore.Qt.Horizontal)
        self.seekBar.setInvertedAppearance(False)
        self.seekBar.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.seekBar.setTickInterval(0)
        self.seekBar.setObjectName("seekBar")
        self.bottomLayout.addWidget(self.seekBar)
        self.lcdTick = QtWidgets.QLCDNumber(Form)
        self.lcdTick.setMinimumSize(QtCore.QSize(77, 0))
        self.lcdTick.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdTick.setStyleSheet("background-color: none; color: black;")
        self.lcdTick.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdTick.setDigitCount(6)
        self.lcdTick.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTick.setObjectName("lcdTick")
        self.bottomLayout.addWidget(self.lcdTick)
        self.playButton = QtWidgets.QPushButton(Form)
        self.playButton.setMinimumSize(QtCore.QSize(0, 32))
        self.playButton.setMaximumSize(QtCore.QSize(32, 16777215))
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/play-icon-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(24, 24))
        self.playButton.setObjectName("playButton")
        self.bottomLayout.addWidget(self.playButton)
        self.verticalLayout.addLayout(self.bottomLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "GyroLog"))
        self.groupBoxRot.setTitle(_translate("Form", "Rotation"))
        self.labelRx.setText(_translate("Form", "Roll"))
        self.labelRy.setText(_translate("Form", "Pitch"))
        self.labelRz.setText(_translate("Form", "Yaw"))
        self.labelRxDeg.setText(_translate("Form", "deg"))
        self.labelRyDeg.setText(_translate("Form", "deg"))
        self.labelRzDeg.setText(_translate("Form", "deg"))
        self.groupBoxRotS.setTitle(_translate("Form", "Angular speed"))
        self.labelRSx.setText(_translate("Form", "Roll"))
        self.labelRSy.setText(_translate("Form", "Pitch"))
        self.labelRSz.setText(_translate("Form", "Yaw"))
        self.labelRSxDegS.setText(_translate("Form", "deg/s"))
        self.labelRSyDegS.setText(_translate("Form", "deg/s"))
        self.labelRSzDegS.setText(_translate("Form", "deg/s"))
        self.labelAltM.setText(_translate("Form", "m"))
        self.labelAlt.setText(_translate("Form", "Alt."))
        self.labelLaunchTime.setText(_translate("Form", "T-00:00:00.000"))

